### ISSUE TITLE
404 error when accessing to a source time series  (and no time series have been created yet)

### ISSUE THREAD

**Issue by mdrio** [tdm-project/tdm-polystore#57]
At this moment, if no time series are available for a given source, the server returns a 404 error. I am not sure this is the right way to handle this, maybe returning an empty list is preferable.

**Comment by mgaggero** [comment]
The same happens when a new source is registered and no timeseries are yet available. It raises an exception for 404 HTTP Code: should return an empty timeserie instead.

**Comment by ilveroluca** [comment]
Resolved by PR #66
